# Copyright 2021 Mavenir
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

######## CNF TEMPLATE DEFINITIONS ###########
global:
  dnPrefix: "mvnr"
  xgvela:
    use_release_ns: false
    create_ns: true
    infra_deploy: true
    infraNodeSelector:
      enabled: true
      labelKey: infra
      labelValue: true
    mgmtNodeSelector:
      enabled: true
      labelKey: mgmt
      labelValue: true
    kafka_svc_fqdn: "oam-kafka.oam-system:9092"
    etcd_svc_fqdn: "192.168.0.8:2379"
    logging_svc_url: "fb-service.xgvela-paas.svc.cluster.local:5175"
    logging_svc_tcp_port: "5170"
    k8s_svc_fqdn: "kubernetes.default.svc.cluster.local"
    zk_svc_fqdn: "oam-zookeeper.oam-system:2181"
    storage_engine: "elasticsearch"
    enable_retrx : "false"
    log_format: "json"
    limaasEnabled: false
    enableXGVelaScaling: false
    storage:
      storageClass: "openebs-standalone"
      isProviderXGVela: false
      isLVPenabled: false
      xgvelaLocalStorageHostPathPrefix: "/data"
      xgvelaLocalStoragePVJobImage: "xgvela-svc-init"
      xgvelaLocalStoragePVJobTag: "v0.3.4"
      hostlocalVolumeSelector: []
    fluentd:
      enabled: false
      output:
        brokers: <output_kafka_url>:<port> # output kafka url
        topic: logs

nf:
  version: "v0.1-xgvela"
  vendorId: "mvnr"
  xgvelaId: "xgvela1" #do not edit
  nfClass: "mgmt"
  nfType: "xgvela"
  nfId: "xgvela1"

  cnftpl_configmap:
    mgmt_cfg:
      create: true
      metaspec:
        annotations:
          configMgmt: enabled
    static_cfg:
      create: true
      metaspec: {}
    env_cfg:
      create: false
      metaspec: {}
  cnftpl_secret:
      create: false
      metaspec: {}
      secretspec: {}
  cnftpl_namespaces:
      create: false
      metaspec: {}
  cnftpl_dashboard:
      create: false
      metaspec: {}
  cnftpl_eventdef:
      create: true
      metaspec: {}
  cnftpl_alertsdef:
      create: false
      metaspec: {}
  cnftpl_metricsdef:
      create: false
      metaspec: {}

###########################################

serviceAccount: topo-gw-account
tmaas:
  init_container:
    image:
      repository: xgvela-svc-init
      tag: 1.0
componentSpec:
  service_fend:
    metaspec: {}
    ports:
      port: "8080"
      targetPort: "8080"
      nodePort: "32233"
    type: NodePort

  deployment:
    replicas: 1

    pod_metaspec:
      labels:
        app: topo-gw
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: /metrics
#        xgvela.com/haaas: '{ "monitoringMode": "hb","mode": "hotStandby","numStandby":"1" }'
#        xgvela.com/vip-networks: '[{"interface": "net1","poolids": ["vipspec1"]}]'
#        k8s.v1.cni.cncf.io/networks: macvlan-hostlocal-0

    topo_gw:
      image: tmaas-gw
      tag: 1.0
      resource:
        limit_memory: 500Mi
        limit_cpu: 500m
        request_memory: 300Mi
        request_cpu: 200m

    cim:
      image: cim
      tag: 1.0
      resource:
        limit_memory: 200Mi
        limit_cpu: 100m
        request_memory: 100Mi
        request_cpu: 50m
      mount:
        type: DirectoryOrCreate
        container_path: /opt/logs
        host_path: /data/logs

etcd_svc_fqdn: "etcd.xgvela-xgvela1-infra-xgvela-xgvela1.svc.cluster.local:2379"
kafka_svc_fqdn: "oam-kafka.oam-system:9092"
k8s_svc_fqdn: "kubernetes.default.svc.cluster.local"
zk_svc_fqdn: "zk-0.zk.xgvela-xgvela1-infra-xgvela-xgvela1.svc.cluster.local:2181,zk-1.zk.xgvela-xgvela1-infra-xgvela-xgvela1.svc.cluster.local:2181,zk-2.zk.xgvela-xgvela1-infra-xgvela-xgvela1.svc.cluster.local:2181"
